Add Docs
ManimCommunity/ManimPango pull request #10
Opened 2021-01-10 12:42 UTC by naveen521kk

A sphinx based docs setup. Should be useful in future, but let it be for now.

2021-01-10 13:29 UTC, naveen521kk commented
View docs at https://manimpango--10.org.readthedocs.build/en/10/

2021-01-11 17:21 UTC, PhilippImhof requested changes
some suggestions

2021-01-11 17:21 UTC, PhilippImhof commented on manimpango/cmanimpango.pyx
> +        """Formatting done for the ``SVG`` file."""
```suggestion
        """Remove element from the SVG file in order to allow comparison."""
```

2021-01-11 17:21 UTC, PhilippImhof commented on manimpango/cmanimpango.pyx
> +    """
```suggestion
    """Formatting for slices of a :py:class:`manim.mobject.svg.text_mobject.Text` object."""
```

2021-01-11 17:21 UTC, PhilippImhof commented on manimpango/cmanimpango.pyx
> +    """
```suggestion
    """Main function called from Manim to render an SVG file from a 
    :py:class:`manim.mobject.svg.text_mobject.Text` object.
    """
```

2021-01-11 17:21 UTC, PhilippImhof commented on manimpango/cmanimpango.pyx
> +        """
```suggestion
        """Main function called from Manim, to render an SVG file from a 
        :py:class:`manim.mobject.svg.text_mobject.MarkupText` object.
        """
```

2021-01-13 12:53 UTC, naveen521kk commented
If it's ok @PhilippImhof can you give an approve?

2021-01-13 15:25 UTC, leotrs requested changes

2021-01-13 15:25 UTC, leotrs commented on manimpango/cmanimpango.pyx
> +    """Formatting for slices of a :py:class:`manim.mobject.svg.text_mobject.Text` object."""
Nitpick: `:py:` is redundant:
```suggestion
    """Formatting for slices of a :class:`manim.mobject.svg.text_mobject.Text` object."""
```

2021-01-13 15:25 UTC, leotrs commented on manimpango/cmanimpango.pyx
> +    """
```suggestion
    """Render an SVG file from a :class:`manim.mobject.svg.text_mobject.Text` object."""
```

2021-01-13 15:25 UTC, leotrs commented on manimpango/cmanimpango.pyx
> +        """
```suggestion
        """Render an SVG file from a :class:`manim.mobject.svg.text_mobject.MarkupText` object."""
```

2021-01-13 15:43 UTC, leotrs approved these changes

2021-01-13 15:47 UTC, naveen521kk commented
I think @leotrs you don't have write access to this repo. or else it should have been merged by now.

2021-01-13 15:47 UTC, merged

2021-01-13 15:48 UTC, leotrs commented
I believe I do have access, I think I just forgot to merge after accepting :sweat_smile:

2021-01-13 15:50 UTC, naveen521kk commented
I had enabled auto-merge which means, it should I have merged if you had writes access.

2021-01-13 16:04 UTC, leotrs commented
Oh snap, then I don't :thinking: