Add option to Load font files
ManimCommunity/manimpango pull request #3
Opened 2020-12-27 08:37 UTC by naveen521kk

For now only for Linux, because they use font config as default backend for the font. While on Windows and Mac, win32 API and CoreText are used respectively. 
We can force Pango to use `fontconfig` backend as default on other OS also, but because of https://gitlab.gnome.org/GNOME/pango/-/issues/523, I am reluctant to do so. Also, this means that Cairo should be compiled with `fontconfig` enabled for this work. Windows users will face no issues in this because the binaries are compiled with fontconfig enabled, but I am not sure on Mac's brew, maybe @PhilippImhof know?
For now, it is conditionally compiled only for Linux. Other OS can't use it for now until we decide over here, whether to force fontconfig usage.

2020-12-27 09:20 UTC, PhilippImhof commented
> Windows users will face no issues in this because the binaries are compiled with fontconfig enabled, but I am not sure on Mac's brew, maybe @PhilippImhof know?

On OS X we have 

```
$ brew uses --installed fontconfig
cairo                                         
pango
ffmpeg                     
```

and 

```
$ port dependents fontconfig
ImageMagick depends on fontconfig
cairo depends on fontconfig
ffmpeg depends on fontconfig
ghostscript depends on fontconfig
```

So we can safely assume that all Manim users will have fontconfig on their Mac.

2020-12-27 09:28 UTC, PhilippImhof commented
Also, I have just tried it (replacing `IF UNAME_SYSNAME == "Linux":` to `IF True:`). Compilation works fine and so does running Manim. All `MarkupText` examples render correctly.

I did not, however, try the new `register_font("/home/roboto.tff")` directive.

2020-12-27 10:10 UTC, naveen521kk commented
Irrc, MacOS has CoreText as default font backend. So this method will not work without forcing Pango to use fontconfig backend. I know things will compile correctly, I have tried myself on windows, but the problem here is it won't work. If you want you could try any new font which isn't installed in you system and try to display it, setting it as font. You would see a warning from Pango in that case, as if I am right `register_font` will not work.

2020-12-27 10:14 UTC, naveen521kk commented
I could make Pango force to use fontconfig backend if needed, but the problem is the users won't be getting any warnings for invalid font and that could be bad, unless the issue I reported to Pango is fixed, https://gitlab.gnome.org/GNOME/pango/-/issues/523. If thats not so important, I will implement this feature as cross platform thing.

2020-12-27 10:29 UTC, PhilippImhof commented
> Irrc, MacOS has CoreText as default font backend. So this method will not work without forcing Pango to use fontconfig backend.

As fontconfig is an explicit dependency for Pango on MacPorts and brew, we can safely assume that Pango does use fontcofig. (I was using font names according to `fc-list` and `fc-match` already before. I have never heard of CoreText before.)

> I know things will compile correctly, I have tried myself on windows

That does not necessarily mean it will work on Mac, no?

> , but the problem here is it won't work. 

What exactly does not work?

> If you want you could try any new font which isn't installed in you system and try to display it, setting it as font. You would see a warning from Pango in that case, as if I am right `register_font` will not work.

```
>>> import manimpango
>>> manimpango.register_font("./Lato-Regular.ttf")
True
>>> manimpango.register_font("foo.ttf")
AssertionError: font doesn't exists at ....
False
>>> 
```

BTW: Note the typo: font doesn't **exist** at

2020-12-27 10:54 UTC, PhilippImhof commented on manimpango/cmanimpango.pyx
> +        assert a.exists(), f"font doesn't exists at {a.absolute()}"
`assert a.exists(), f"font doesn't exist at {a.absolute()}"`

2020-12-27 11:00 UTC, naveen521kk commented
> As fontconfig is an explicit dependency for Pango on MacPorts and brew, we can safely assume that Pango does use fontcofig. (I was using font names according to fc-list and fc-match already before. I have never heard of CoreText before.)

Default is CoreText (one which MacOS provides), but fontconfig can also be used but Pango need to forced to use it.

> What exactly does not work?

The font register and it's ok. But you can't use that family name as part of `text2svg` functions, because it will produce ugly output. Maybe try out? Use the same example you provided, find its family name and pass it to `Text`, you will see a warning there and that font will not be used. Have a look at https://developer.gnome.org/pango/stable/pango-Cairo-Rendering.html

2020-12-28 13:36 UTC, naveen521kk commented
@PhilippImhof Looks like people would like to have font warnings. So this can be merged as-is. Can you give a approve? Let me try the auto-merge feature.

2020-12-28 13:40 UTC, PhilippImhof requested changes
LGTM, just a small change in the docstring.

Another question: Is `register_font` not planned to be made available for Mac and Windows? Otherwise the `UNAME_SYSNAME== "Linux"` part should be changed.

2020-12-28 13:40 UTC, PhilippImhof commented on manimpango/cmanimpango.pyx
> +                False means there is a Unknow Error
```suggestion
                False means there was an unknown error
```

2020-12-28 13:41 UTC, PhilippImhof approved these changes

2020-12-28 13:44 UTC, naveen521kk commented
> Another question: Is register_font not planned to be made available for Mac and Windows? Otherwise the UNAME_SYSNAME== "Linux" part should be changed.

At least, that's what the poll suggested. Once pango fixes https://gitlab.gnome.org/GNOME/pango/-/issues/523 then it would be just removing the `IF` and indent it properly.

2020-12-28 13:46 UTC, merged

2020-12-28 13:46 UTC, naveen521kk commented
yay, it worked.