Updates to CI
ManimCommunity/ManimPango pull request #68
Opened 2021-12-04 10:08 UTC by naveen521kk

- Don't use `windows-2016` (it's nearing EOL) see #66 
- Upgrade dependencies for the build
- Probably try enabling Arm wheels for macOS.
- Don't build subprojects manually.

2021-12-04 10:17 UTC, PhilippImhof approved these changes
LGTM. Do we have to do something about the failing build?

```
cibuildwheel 2.x no longer supports Python < 3.6. Please use the 1.x series or update CIBW_SKIP
Error: Command source packing/build_pango_mac.sh && pip install cython && cd manimpango && cythonize cmanimpango.pyx -3 -k -f && cd ../ && pip install . && pkg-config --libs pango failed with code 1. None

Error: Process completed with exit code 1.
```

2021-12-04 10:21 UTC, naveen521kk commented
> Do we have to do something about the failing build?

Ah, sorry I didn't mark it as a draft. It's still a WIP.

2021-12-04 10:24 UTC, PhilippImhof commented
> Ah, sorry I didn't mark it as a draft. It's still a WIP.

OK, fine. You actually seemed to even have requested a review :)

2021-12-04 10:26 UTC, naveen521kk commented
> You actually seemed to even have requested a review :)

I guess that's because you are a Code owner here,

2021-12-05 08:44 UTC, naveen521kk commented
@PhilippImhof This PR is ready and waiting for your review :).

2021-12-05 08:57 UTC, PhilippImhof requested changes
Very well done. I have just a few nitpicks w.r.t consistent language use.

2021-12-05 08:57 UTC, PhilippImhof commented on tests/test_fonts.py
>      assert "Pango-WARNING **" not in captured, "Looks like pango raised a warning?"
```suggestion
    assert "Pango-WARNING **" not in captured, "Looks like Pango raised a warning?"
```

2021-12-05 08:57 UTC, PhilippImhof commented on .github/workflows/build.yml
>        - name: Build wheels(Windows)
```suggestion
      - name: Build wheels (Windows)
```

2021-12-05 08:57 UTC, PhilippImhof commented on .github/workflows/build.yml
> +    name: Test Wheels on ${{ matrix.os }}-${{ matrix.platform_id }}-${{ matrix.python-version }}
```suggestion
    name: Test wheels on ${{ matrix.os }}-${{ matrix.platform_id }}-${{ matrix.python-version }}
```

2021-12-05 08:57 UTC, PhilippImhof commented on .github/workflows/build.yml
> +      - name: Install Test Dependencies
```suggestion
      - name: Install test dependencies
```

2021-12-05 08:57 UTC, PhilippImhof commented on .github/workflows/build.yml
> +      - name: Install Wheels
```suggestion
      - name: Install wheels
```

2021-12-05 08:57 UTC, PhilippImhof commented on .github/workflows/build.yml
>        - name: Publish (Release)
```suggestion
      - name: Publish release
```

2021-12-05 08:57 UTC, PhilippImhof commented on .github/workflows/build.yml
> +    name: Build and Test Wheels Successfully
```suggestion
    name: Building and testing of wheels: success
```

2021-12-05 08:57 UTC, PhilippImhof commented on .github/workflows/build.yml
> +        run: echo Build and Test Wheels Successfully
```suggestion
        run: echo "Building and testing of wheels: success"
```

2021-12-05 08:57 UTC, PhilippImhof commented on packing/build_pango_mac.sh
> +echo "Getting Patch and Applying patch for Cairo Build"
```suggestion
echo "Fetching and applying patch for Cairo build"
```

2021-12-05 08:57 UTC, PhilippImhof commented on packing/build_pango_mac.sh
>  echo "::group::Building and Install proxy-libintl"
```suggestion
echo "::group::Building and installing proxy-libintl"
```

2021-12-05 08:57 UTC, PhilippImhof commented on packing/build_pango_mac.sh
>  echo "::group::Building and Install Fontconfig"
```suggestion
echo "::group::Building and installing Fontconfig"
```

2021-12-05 08:57 UTC, PhilippImhof commented on packing/build_pango_mac.sh
> +echo "::group::Building and Install Glib"
```suggestion
echo "::group::Building and installing Glib"
```

2021-12-05 08:57 UTC, PhilippImhof commented on packing/build_pango_mac.sh
>  echo "::group::Building and Installing Cairo"
```suggestion
echo "::group::Building and installing Cairo"
```

2021-12-05 08:57 UTC, PhilippImhof commented on packing/build_pango_mac.sh
>  echo "::group::Building and Installing Harfbuzz"
```suggestion
echo "::group::Building and installing Harfbuzz"
```

2021-12-05 08:57 UTC, PhilippImhof commented on packing/build_pango_mac.sh
>  echo "::group::Buildling and Installing Pango"
```suggestion
echo "::group::Building and installing Pango"
```

2021-12-05 10:43 UTC, naveen521kk commented
@PhilippImhof Thanks for the review. It would be nice if you could test the macOS wheels also https://github.com/ManimCommunity/ManimPango/suites/4557070397/artifacts/122415312

2021-12-12 08:47 UTC, PhilippImhof commented
I currently have some environment problems on my machine and thus cannot properly test the macOS wheels. But I think we can go for it, no?

2021-12-12 08:48 UTC, naveen521kk commented
> But I think we can go for it, no?

Yeah, I guess at least it works on Github's machine.

2021-12-12 08:49 UTC, PhilippImhof approved these changes
LGTM

2021-12-12 08:53 UTC, merged

2021-12-12 08:57 UTC, naveen521kk commented
I'll do a release later today. I guess it should be a major bump right because of https://github.com/ManimCommunity/ManimPango/pull/65